# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'
# add the Firebase pod for Google Analytics
# add pods for any other desired Firebase products
pod 'Firebase/Auth'
# https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for Auction
pod 'ImagePicker'

end
